### ISSUE TITLE
Should parent object must be derived from DisposeNotifyingObject?

### ISSUE THREAD

**Issue by scott-xu** [ninject/Ninject.Extensions.NamedScope#12]
Hi @remogloor , a quick question: should the parent object must be derived from `DisposeNotifyingObject`?
I saw most of the fake parent types in unit test are derived from `DisposeNotifyingObject` and when I removed the inheritance, the UT failed.

**Comment by BrunoJuchli** [comment]
Also note that you don't need to derive from `DisposeNotifyingObject` but rather implementing `INotifyWhenDisposed` is enough.
