### ISSUE TITLE
3.0.2 Stable NuGet package?

### ISSUE THREAD

**Issue by megakid** [ninject/Ninject.Extensions.NamedScope#8]
Is there any reason why 3.0.2 isn't stable on NuGet? 

We're trying to generate stable NuGet packages internally but need to use the unstable NamedScope extension (for the NamedScope creation method that doesn't appear in 3.0.0.5 - the last stable version on nuget.org).  It seems if a dependency is pre-release then the package gets labelled as pre-release.

Is there a genuine concern that 3.0.2 isn't stable?

Cheers,

James

**Comment by scott-xu** [comment]
not a issue anymore.
